name: alt Workflows 

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Initializing environment
         run: |
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           docker rmi `docker images -q`
           sudo apt-get remove account-plugin-facebook account-plugin-flickr account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common mcp-account-manager-uoa python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* 
           sudo -E apt-get clean
           sudo -E apt-get -qq update
       - name: Checkout
         uses: actions/checkout@main
       
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: initialization
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GitHubName }}
           git config --global user.email ${{ secrets.GitHubMail }}
           git config --global credential.helper store
           echo "https://Col-Serra:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
           
       
       - name: cloning repo
         continue-on-error: true
         run: |
           git clone https://github.com/Col-Serra/slam-mirrorbot
       - name: Running alt Bot 
         timeout-minutes: 300
         continue-on-error: true
         run: |
           cd  slam-mirrorbot
           cp config_sample.env config.env
           docker build . -t mirror-bot && docker run -p 80:80 mirror-bot
           
       - name: Loop workflow
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
           cd loop || exit 1
           echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
           git add looper.txt
           git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
           git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
