name: ca Workflows 

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - name: Setup tmate session
         uses: mxschmitt/action-tmate@v3
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: initialization
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GitHubName }}
           git config --global user.email ${{ secrets.GitHubMail }}
           git config --global credential.helper store
           echo "https://Col-Serra:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
           
       
       - name: cloning repo
         continue-on-error: true
         run: |
           git clone https://github.com/Col-Serra/Userge
       - name: Running alt Bot 
         timeout-minutes: 300
         continue-on-error: true
         run: |
           cd  Userge
           cp resources/resources.sh config.env
           docker build . -t userge && docker run -d --restart on-failure --name userge_1 userge
           
       - name: Loop workflow
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
           cd loop || exit 1
           echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
           git add looper.txt
           git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
           git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
